### ISSUE TITLE
Скрипт перестал работать

### ISSUE THREAD

**Issue by andrychuyko** [TerAnYu/yota_check#1]
Привет. Скрипт перестал работать, и мне кажется потому, что yota поменяла алгоритм продления. 

Я сильно не разбираюсь, но сначала загружается страница hello.yota.ru, она подгружает ajaxом https://hello.yota.ru/light/, которая вроде делает какие-то важные куки, а при нажатии кнопки "Продлить", POST запрос на https://hello.yota.ru/wa/v1/service/temp с телом запроса {"serviceCode":"light"}

Это пока все, что удалось мне раскопать, но когда это все делаешь curlом, что-то не срабатывает

**Comment by TerAnYu** [comment]
Приветствую!
Попробую посмотреть что там происходит, просто перестал уже пользоваться и не знаю, может уже и заблокировали...

**Comment by TerAnYu** [comment]
К сожалению реализовать нечто подобное не смог, но, можеь быть, если посоображать над этими проектами, то, возможно, это поможет.
[yota-script](https://github.com/mgarmash/yota-script)
[yota](https://github.com/velsa/yota)

И да, на OpenWrt не нашёл этих библиотек и не получилось заставить их работать :(

**Comment by TerAnYu** [comment]
К сожалению я не смог помочь и Вы сами себе решили задачу: https://github.com/andrychuyko/yota_check
